sudo: true
language: python

env:
  - VARIANT=source/1-Drawing/Test-Reglar.ufo
  - SHELL_PATH=build.sh

before_script: 
  - sudo apt-get install -y shellcheck

script: 
  - "shellcheck $SHELL_PATH"

notifications:
  email: false
